/**
 * Splitting of `$…$` LaTeX out of ordinary text.
 *
 * Teachers routinely paste explanations generated by an AI assistant, which
 * come with dollar-delimited maths (`$p^+$`, `$N(p^+) = N(e^-) = Z$`). The
 * editor converts those into real math nodes on open, but lessons saved
 * before that existed still hold the raw text -- so the student renderer
 * parses them too rather than showing stray dollar signs.
 */

export type MathSegment = { type: "text"; value: string } | { type: "math"; latex: string };

/**
 * Requires a non-space immediately inside both delimiters and forbids `$`,
 * newlines, and spaces adjacent to the delimiters. That is what keeps prices
 * ("стоит $5 и $10 за штуку") from being swallowed as one formula: there, the
 * closing delimiter is preceded by a space.
 */
const MATH_PATTERN = /\$(?![\s$])((?:[^$\n])*?[^\s$])\$/g;

export function hasMath(text: string): boolean {
  MATH_PATTERN.lastIndex = 0;
  return MATH_PATTERN.test(text);
}

export function parseMath(text: string): MathSegment[] {
  const segments: MathSegment[] = [];
  let lastIndex = 0;

  MATH_PATTERN.lastIndex = 0;
  for (const match of text.matchAll(MATH_PATTERN)) {
    const start = match.index ?? 0;
    if (start > lastIndex) segments.push({ type: "text", value: text.slice(lastIndex, start) });
    segments.push({ type: "math", latex: match[1] });
    lastIndex = start + match[0].length;
  }
  if (lastIndex < text.length) segments.push({ type: "text", value: text.slice(lastIndex) });

  return segments;
}
